name: Contracts CI

on:
  - push
  - pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run coverage
        run: npx hardhat coverage 

      - name: Run coveralls
        uses: coverallsapp/github-action@master     
        with:
          github-token: ${{ secrets.CRED }}
