on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
             npm install 
             npm test
             make test-coverage
     - name: Coveralls
       uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.CRED }}
